### ISSUE TITLE
After adding a new term in the term library, the count of the term type doesn't update in the "Edit term" tab

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#122]
For example, if you add a new reference physical entity to the model, the number in parentheses next to "Reference Physical Entity" in the "Edit term" tab remains the same.

**Comment by thompsct** [comment]
Fixed.

**Comment by maxneal** [comment]
Confirmed.

**Comment by maxneal** [comment]
This works OK for custom physical entities, but when you create a new custom physical *process*, the count still doesn't update in the "Edit term" tab.

**Comment by thompsct** [comment]
Fixed for processes.

**Comment by maxneal** [comment]
Confirmed.
