### ISSUE TITLE
Model-level editor becomes unreachable during annotation process

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#23]
The list of model-level properties in the upper left of the annotator becomes unresponsive to clicks if I do this:

1) Open new Annotator using tree view
2) Click on "Description" in the list of model-level properties
3) Enter text in Description field
4) Click in another field, green check mark will appear next to "Description" in model-level properties
5) Double-click on a submodel in the tree view to expand it (note that the annotation panel for the sub model does not appear)
6) Click on a codeword that is part of the submodel
7) Clicking on the list of model-level properties after this point will not show the model-level annotation editor

**Comment by thompsct** [comment]
Fixed. The update method in AnnotatorTab needed to return if a Model Metadata item was selected.

**Comment by maxneal** [comment]
I can now get back to the model-level annotator panel, but the additional bug in step 5 is still present.

**Comment by thompsct** [comment]
So I've figured out the cause of this problem. When in tree view, the bit of code that makes the annotator panel change only fires when a new branch is selected. So, even though the model annotator pane is displayed, the tree still has a node selected and clicking on it again does not result in the 'valuechanged' event getting fired. 

I'm working on a fix.

**Comment by thompsct** [comment]
Got it, try it now.

**Comment by maxneal** [comment]
OK looks like it's working right. Closing issue. Thanks!
