### ISSUE TITLE
"Cancel" option in save dialog doesn't prevent SG from quitting

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#35]
If I load a model, make an edit to the annotations and then quit SemGen, I get the "Save changes?" prompt. 

If I then hit Cancel, which should abort the quit process, SG still quits.

**Comment by thompsct** [comment]
Fixed

**Comment by maxneal** [comment]
Works properly if I quit SG by clicking the frame close button or by selecting "Quit SemGen" from the "File" menu. 

But the bug is still present if I use command-Q to quit, or select "Quit SemGen" from the "SemGen" menu in the Mac menu bar.

**Comment by thompsct** [comment]
What version of OSX are you using? This issue appears MacOS related.

**Comment by maxneal** [comment]
10.7.5 (Lion)

**Comment by maxneal** [comment]
duplicate of #108
