### ISSUE TITLE
Annotation status indicators don't refresh after model-to-model annotation copy

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#52]
For example, if you open the original Niederer CellML model and import all the annotations from the annotated SemSim version, the status indicators for the codewords don't refresh after import is complete.

**Comment by thompsct** [comment]
I don't believe the model annotations are currently setup to be imported. Definitely something to add.

**Comment by maxneal** [comment]
We can currently do this using the "Annotate codewords using data from identical codewords..." button in the Annotator toolbar. It imports the annotations for all codewords with matching names, but it just doesn't refresh the annotation status indicators when it's done. I've used this successfully on several occasions during the CellML annotation and PHN merging efforts.

**Comment by thompsct** [comment]
Ah, I thought you were referring to the model level annotations.

**Comment by maxneal** [comment]
Ah I see - I was talking about the codeword and submodel indicators, but that reminds me that we need to make sure the annotation copier also includes the model-level annotations.

**Comment by maxneal** [comment]
I checked to see if this is still an issue in the latest SG version and it is.  Model annotations still not being imported as well.

**Comment by thompsct** [comment]
This should be fixed.

**Comment by maxneal** [comment]
This is still not working quite right. If using the flat list view for codewords in the Annotator, the indicators and property marker types are not immediately updated on annotation import. Switching to tree view then back to flat list view updates them.

**Comment by thompsct** [comment]
Try it now.

**Comment by maxneal** [comment]
Did you push a fix to the master already? Didn't see it.

**Comment by thompsct** [comment]
There was another commit I had to pull before it would push. Try again.

**Comment by maxneal** [comment]
Looks like it's working correctly now.
